# Amazon Review AI Optimizer - Week 1 Configuration
# Complexity-based routing system configuration

data_loading:
  sample_size: 1000
  categories: ["Electronics", "Books", "Home_and_Garden"]
  
openrouter:
  base_url: "https://openrouter.ai/api/v1"
  timeout: 30
  max_retries: 3
  rate_limit: 10  # requests per second

models:
  # Model tier configuration for complexity-based routing
  ultra_lightweight:
    models:
      - name: "openai/gpt-4o-mini"
        cost_per_million: 0.15
        max_tokens: 100
    complexity_threshold: 0.2
    
  lightweight:
    models:
      - name: "anthropic/claude-3-haiku"
        cost_per_million: 0.25
        max_tokens: 150
    complexity_threshold: 0.4
    
  medium:
    models:
      - name: "openai/gpt-3.5-turbo"
        cost_per_million: 0.50
        max_tokens: 200
    complexity_threshold: 0.7

complexity_analysis:
  # Multi-dimensional complexity scoring weights
  technical_weight: 0.35
  sentiment_weight: 0.25
  length_weight: 0.20
  domain_weight: 0.20
  
  # Technical keyword categories
  technical_keywords:
    Electronics: ["battery", "processor", "memory", "performance", "compatibility"]
    Books: ["plot", "character", "narrative", "author", "writing"]
    Home_and_Garden: ["quality", "durability", "installation", "design", "material"]

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
